# Generated by Django 4.2.9 on 2026-05-09 18:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('noise', 'Noise Complaint'), ('crime', 'Crime'), ('transit', 'Transit'), ('sanitation', 'Sanitation'), ('infrastructure', 'Infrastructure'), ('emergency', 'Emergency'), ('other', 'Other')], default='other', max_length=50)),
                ('source', models.CharField(choices=[('nyc_311', 'NYC 311'), ('nypd', 'NYPD Crime Stats'), ('mta', 'MTA Alerts'), ('fema', 'FEMA'), ('chicago', 'Chicago Data Portal')], max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20)),
                ('borough', models.CharField(blank=True, max_length=100)),
                ('neighborhood', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('external_id', models.CharField(max_length=200, unique=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['category', 'timestamp'], name='incidents_i_categor_982af4_idx'), models.Index(fields=['source', 'timestamp'], name='incidents_i_source_96246f_idx'), models.Index(fields=['borough', 'timestamp'], name='incidents_i_borough_53bf7c_idx'), models.Index(fields=['external_id'], name='incidents_i_externa_87a4a1_idx')],
            },
        ),
    ]
